safe:        true
markdown: kramdown
exclude: [node_modules, bower_components, vendor]
url: https://jhipster.io
github_repository_url: https://github.com/jhipster-io/jhipster-io.github.io
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-redirect-from
  - jemoji
defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
